version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - WEBUI_PORT=8080
    volumes:
      - /home/julien/docker-setup/qbittorrent/config:/config
      - /mnt/nas/torrents:/nas/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/radarr/config:/config
      - /mnt/nas:/nas
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000/
      - UMASK=002
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/prowlarr/config:/config
    restart: unless-stopped
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/sonarr/config:/config
      - /mnt/nas:/nas
    restart: unless-stopped
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:nightly
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/readarr/config:/config
      - /mnt/nas:/nas
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/bazarr:/config
      - /mnt/nas:/nas
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/calibre/config:/config
      - /mnt/nas:/nas
    ports:
      - 8083:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/calibre-web:/config
      - /mnt/nas:/nas
    ports:
      - 8084:8083
    restart: unless-stopped
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/mylar:/config
      - /mnt/nas:/nas
    ports:
      - 8090:8090
    restart: unless-stopped
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unpackerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - /mnt/nas:/nas
    restart: unless-stopped
    # Get the user:group correct so unpackerr can read and write to your files.
    user: 1000:1000
    #user: 1000:1000
    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    # Remove apps and feature configs you do not use or need. 
    # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
    environment:
      - TZ=Europe/Brussels
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://192.168.0.121:8989
      - UN_SONARR_0_API_KEY=${SONARR_API}
      - UN_SONARR_0_PATHS_0=/nas/torrents/tv-sonarr
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://192.168.0.121:7878
      - UN_RADARR_0_API_KEY=${RADARR_API}
      - UN_RADARR_0_PATHS_0=/nas/torrents/radarr
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=http://192.168.0.121:8787
      - UN_READARR_0_API_KEY=${READARR_API}
      - UN_READARR_0_PATHS_0=/downloads
      - UN_READARR_0_PROTOCOLS=torrent
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=false
      - UN_READARR_0_DELETE_DELAY=5m

    security_opt:
      - no-new-privileges:true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/julien/docker-setup/sabnzbd/config:/config
      - /mnt/nas:/nas
    ports:
      - 8085:8080
    restart: unless-stopped
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /home/julien/docker-setup/komga/config:/config
      - /mnt/nas:/nas
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 25600:25600
    # remove the whole environment section if you don't need it
    restart: unless-stopped
